'use strict';

const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { URL, URLSearchParams } = require('url');
let WebSocket;
try { WebSocket = require('ws'); } catch { WebSocket = null; }

const ROOT = __dirname;
const PUBLIC = path.join(ROOT, 'public');
const DATA = process.env.DATA_DIR ? path.resolve(process.env.DATA_DIR) : path.join(ROOT, 'data');
fs.mkdirSync(DATA,{recursive:true});
const CONFIG_FILE = path.join(DATA, 'config.json');
const STATE_FILE = path.join(DATA, 'state.json');
const sessions = new Map();
const oauthStates = new Map();
const deviceAttempts = new Map();
const DEFAULT_SCOPES = 'user:read:chat moderator:read:chatters';

const runtime = {
  adminToken:'', adminTwitch:null, ws:null, wsStatus:'DISCONNECTED', wsSessionId:'',
  chatSubscribed:false, streamSubscribed:false, streamStatus:'UNKNOWN', streamOnline:false,
  streamStartedAt:null, lastStreamCheck:0, lastStreamError:'', lastChatAt:0,
  lastWatchtimePoll:0, lastWatchtimeUsers:0, lastWatchtimeError:'', watchtimeTimer:null,
  reconnectTimer:null
};

function deepClone(x){ return JSON.parse(JSON.stringify(x)); }
function jsonRead(file, fallback){ try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return deepClone(fallback);} }
function jsonWrite(file, value){ const tmp=file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(value,null,2),'utf8');fs.renameSync(tmp,file); }
function loadConfig(){
  const c=Object.assign({clientId:'',authMode:'device',loginScopes:DEFAULT_SCOPES,adminTwitchLogin:'sovara_',adminTwitchUserId:'',port:4177,publicBaseUrl:''},jsonRead(CONFIG_FILE,{}));
  if(process.env.TWITCH_CLIENT_ID)c.clientId=String(process.env.TWITCH_CLIENT_ID).trim();
  if(process.env.TWITCH_AUTH_MODE)c.authMode=String(process.env.TWITCH_AUTH_MODE).trim();
  if(process.env.TWITCH_LOGIN_SCOPES)c.loginScopes=String(process.env.TWITCH_LOGIN_SCOPES).trim();
  if(process.env.ADMIN_TWITCH_LOGIN)c.adminTwitchLogin=String(process.env.ADMIN_TWITCH_LOGIN).trim();
  if(process.env.ADMIN_TWITCH_USER_ID)c.adminTwitchUserId=String(process.env.ADMIN_TWITCH_USER_ID).trim();
  if(process.env.PUBLIC_BASE_URL)c.publicBaseUrl=String(process.env.PUBLIC_BASE_URL).trim().replace(/\/$/,'');
  if(process.env.PORT)c.port=Number(process.env.PORT)||c.port;
  return c;
}
function saveConfig(c){ jsonWrite(CONFIG_FILE,c); }
function isProduction(){return process.env.NODE_ENV==='production'||process.env.RAILWAY_ENVIRONMENT_NAME==='production';}
function requestBaseUrl(req,config=loadConfig()){if(config.publicBaseUrl)return config.publicBaseUrl;const proto=String(req.headers['x-forwarded-proto']||'http').split(',')[0].trim();const host=String(req.headers['x-forwarded-host']||req.headers.host||`localhost:${config.port}`).split(',')[0].trim();return `${proto}://${host}`;}
function baseState(){ return {version:5,giveaway:{title:'SOVARA Giveaway',prizeRub:5000,ticketCost:300,maxTickets:10,minParticipants:10,durationDays:30,startedAt:null,endsAt:null,winner:null},settings:{pointsPerMinute:1,pointsPerMessage:1,watchtimePollMinutes:5,messagePointsEnabled:true,watchtimePointsEnabled:true,countMessagesOffline:false},users:{},processedMessages:{},audit:[]}; }
function now(){ return Date.now(); }
function esc(s){ return String(s??'').trim(); }
function id(bytes=24){ return crypto.randomBytes(bytes).toString('hex'); }
function safeEqual(a,b){ return esc(a).toLowerCase()===esc(b).toLowerCase(); }
function defaultProfile(){return {prizeType:'',steamLogin:'',steamCurrency:'RUB',steamFriendCode:'',steamGameUrl:'',ozonEmail:'',donationGame:'',donationAccount:'',contactVk:'',contactTelegram:''};}
function defaultSettings(){return {pointsPerMinute:1,pointsPerMessage:1,watchtimePollMinutes:5,messagePointsEnabled:true,watchtimePointsEnabled:true,countMessagesOffline:false};}
function normalizeUser(u){
  u.points=Number.isFinite(Number(u.points))?Math.max(0,Math.floor(Number(u.points))):0;
  u.tickets=Number.isFinite(Number(u.tickets))?Math.max(0,Math.floor(Number(u.tickets))):0;
  u.totalWatchMinutes=Number.isFinite(Number(u.totalWatchMinutes))?Math.max(0,Math.floor(Number(u.totalWatchMinutes))):0;
  u.profile=Object.assign(defaultProfile(),u.profile||{});
  u.chatHistory=Array.isArray(u.chatHistory)?u.chatHistory.slice(-200):[];
  u.pointsPausedUntil=Number.isFinite(Number(u.pointsPausedUntil))?Math.max(0,Number(u.pointsPausedUntil)):0;
  u.winnerBlacklisted=!!u.winnerBlacklisted;
  u.winnerBlacklistedAt=Number.isFinite(Number(u.winnerBlacklistedAt))?Math.max(0,Number(u.winnerBlacklistedAt)):0;
  u.createdAt=Number(u.createdAt)||now();u.updatedAt=Number(u.updatedAt)||now();
  return u;
}
function migrateState(s){
  const b=baseState();s=Object.assign(b,s||{});s.giveaway=Object.assign(b.giveaway,s.giveaway||{});s.settings=Object.assign(defaultSettings(),s.settings||{});s.users=s.users||{};s.processedMessages=s.processedMessages||{};s.audit=Array.isArray(s.audit)?s.audit.slice(-2000):[];s.version=5;
  Object.keys(s.users).forEach(k=>normalizeUser(s.users[k]));
  // Old prototype could already have a 7-day end date. Upgrade it to 30 days from the original start.
  if(s.giveaway.startedAt && s.giveaway.durationDays===30){const desired=s.giveaway.startedAt+30*86400000;if(!s.giveaway.endsAt||s.giveaway.endsAt<s.giveaway.startedAt+29*86400000)s.giveaway.endsAt=desired;}
  cleanupProcessed(s);return s;
}
function loadState(){return migrateState(jsonRead(STATE_FILE,baseState()));}
function saveState(s){jsonWrite(STATE_FILE,migrateState(s));}
function cleanupProcessed(s){const cut=now()-30*86400000;const keys=Object.keys(s.processedMessages||{}).sort((a,b)=>(s.processedMessages[b]||0)-(s.processedMessages[a]||0));keys.forEach((k,i)=>{if(i>=10000||s.processedMessages[k]<cut)delete s.processedMessages[k];});}
function ticketCount(points,g){return Math.min(Number(g.maxTickets||10),Math.floor(Math.max(0,Number(points)||0)/Number(g.ticketCost||300)));}
function syncTickets(u,g){u.tickets=ticketCount(u.points,g);}
function getUser(state,twitch){const key=String(twitch.id);if(!state.users[key])state.users[key]=normalizeUser({twitchUserId:key,login:twitch.login||key,displayName:twitch.displayName||twitch.login||key,avatar:twitch.avatar||'',points:0,tickets:0,totalWatchMinutes:0,profile:defaultProfile(),chatHistory:[],pointsPausedUntil:0,createdAt:now(),updatedAt:now()});const u=normalizeUser(state.users[key]);u.login=twitch.login||u.login;u.displayName=twitch.displayName||u.displayName;u.avatar=twitch.avatar||u.avatar;syncTickets(u,state.giveaway);u.updatedAt=now();return u;}
function getOrCreateChatUser(state,e){return getUser(state,{id:String(e.userId),login:e.login||String(e.userId),displayName:e.displayName||e.login||String(e.userId),avatar:''});}
function profileValidation(profile){const p=Object.assign(defaultProfile(),profile||{}),errors={};const tg=esc(p.contactTelegram),vk=esc(p.contactVk);if(!tg&&!vk)errors.contact='Укажите хотя бы Telegram или VK.';if(tg&&!/^@?[A-Za-z0-9_]{5,32}$/.test(tg))errors.contactTelegram='Telegram: @username или username.';if(vk&&!/^(https?:\/\/)?(www\.)?vk\.(com|ru)\/[A-Za-z0-9_.-]+\/?$/i.test(vk))errors.contactVk='Укажите ссылку на профиль VK.';const allowed=['steam_balance','steam_game','ozon','game_donation'];if(!allowed.includes(p.prizeType))errors.prizeType='Выберите желаемый приз.';if(p.prizeType==='steam_balance'){if(!/^[^\x00-\x1f\x7f]{2,64}$/.test(esc(p.steamLogin)))errors.steamLogin='Укажите Steam login.';if(!['RUB','KZT','USD','EUR'].includes(esc(p.steamCurrency).toUpperCase()))errors.steamCurrency='Выберите валюту из списка.';}if(p.prizeType==='steam_game'){if(!/^\d{5,12}$/.test(esc(p.steamFriendCode)))errors.steamFriendCode='Код дружбы должен состоять из цифр.';if(!/^https:\/\/store\.steampowered\.com\/app\/\d+/i.test(esc(p.steamGameUrl)))errors.steamGameUrl='Нужна ссылка на игру в Steam Store.';}if(p.prizeType==='ozon'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(esc(p.ozonEmail)))errors.ozonEmail='Укажите корректную почту.';if(p.prizeType==='game_donation'){if(esc(p.donationGame).length<2)errors.donationGame='Укажите игру.';if(esc(p.donationAccount).length<2)errors.donationAccount='Укажите игровой ID / ник / сервер.';}return {ok:Object.keys(errors).length===0,errors};}
function prizeLabel(type){return ({steam_balance:'Пополнение Steam',steam_game:'Игра в Steam',ozon:'Сертификат Ozon',game_donation:'Донат в игру'})[type]||'Не выбран';}
function publicUser(u){const v=profileValidation(u.profile);return {twitchUserId:u.twitchUserId,login:u.login,displayName:u.displayName,avatar:u.avatar||'',points:u.points,tickets:u.tickets,participating:v.ok&&u.tickets>0};}
function privateUser(u){const v=profileValidation(u.profile);return Object.assign(publicUser(u),{profile:u.profile,profileComplete:v.ok,profileErrors:v.errors,totalWatchMinutes:u.totalWatchMinutes,prizeLabel:prizeLabel(u.profile.prizeType),pointsPausedUntil:u.pointsPausedUntil||0,isPointsPaused:(u.pointsPausedUntil||0)>now(),winnerBlacklisted:!!u.winnerBlacklisted,winnerBlacklistedAt:u.winnerBlacklistedAt||0,chatCount:u.chatHistory.length,lastChat:u.chatHistory.length?u.chatHistory[u.chatHistory.length-1]:null});}
function countEligible(state){return Object.values(state.users).map(normalizeUser).filter(u=>profileValidation(u.profile).ok&&u.tickets>0).length;}
function winnerPool(state){return Object.values(state.users).map(normalizeUser).filter(u=>profileValidation(u.profile).ok&&u.tickets>0&&!u.winnerBlacklisted);}
function drawWinner(state){const pool=winnerPool(state);const total=pool.reduce((n,u)=>n+u.tickets,0);if(total<=0)return null;let pick=crypto.randomInt(1,total+1),cursor=0;for(const u of pool){cursor+=u.tickets;if(pick<=cursor)return {twitchUserId:u.twitchUserId,login:u.login,displayName:u.displayName,tickets:u.tickets,drawTicket:pick,totalEligibleTickets:total,drawnAt:now()};}return null;}
function recalcGiveaway(state){const g=state.giveaway,eligible=countEligible(state);if(!g.startedAt&&eligible>=Number(g.minParticipants||10)){g.startedAt=now();g.endsAt=g.startedAt+Number(g.durationDays||30)*86400000;state.audit.push({at:now(),type:'giveaway_started',eligible});}return eligible;}
function addAudit(s,type,data={}){s.audit.push({at:now(),type,data});s.audit=s.audit.slice(-2000);}
function pointsAllowed(u){return !(u.pointsPausedUntil&&u.pointsPausedUntil>now());}
function applyPoints(state,u,amount,source){amount=Math.floor(Number(amount)||0);if(amount<=0)return {added:0,reason:'invalid'};if(source!=='admin'&&!pointsAllowed(u))return {added:0,reason:'paused'};u.points+=amount;syncTickets(u,state.giveaway);u.updatedAt=now();addAudit(state,'points_added',{twitchUserId:u.twitchUserId,amount,source});return {added:amount,reason:'ok'};}
function addChatHistory(u,item){u.chatHistory.push(item);u.chatHistory=u.chatHistory.slice(-200);}
function processChatMessage(state,evt,{streamOnline=runtime.streamOnline,source='eventsub'}={}){
  const mid=String(evt.messageId||'').slice(0,200);if(mid&&state.processedMessages[mid])return {counted:false,reason:'duplicate'};if(mid)state.processedMessages[mid]=now();
  const u=getOrCreateChatUser(state,evt);const settings=state.settings;let counted=false,reason='';
  if(!settings.messagePointsEnabled)reason='message_points_disabled';
  else if(u.twitchUserId===String(loadConfig().adminTwitchUserId||''))reason='broadcaster';
  else if(!pointsAllowed(u))reason='paused';
  else if(!streamOnline&&!settings.countMessagesOffline)reason='stream_offline';
  else {applyPoints(state,u,settings.pointsPerMessage,'chat');counted=true;reason=streamOnline?'online':'offline_test';}
  const row={at:now(),messageId:mid||id(8),text:String(evt.text||'').slice(0,500),counted,reason,streamOnline:!!streamOnline,source};addChatHistory(u,row);u.updatedAt=now();runtime.lastChatAt=row.at;return {counted,reason,user:privateUser(u),row};
}

function parseCookies(req){const out={};(req.headers.cookie||'').split(';').forEach(x=>{const i=x.indexOf('=');if(i>0)out[x.slice(0,i).trim()]=decodeURIComponent(x.slice(i+1));});return out;}
function sessionFor(req){const sid=parseCookies(req).sovara_session,s=sid&&sessions.get(sid);if(!s||s.expiresAt<now()){if(sid)sessions.delete(sid);return null;}return s;}
function createSession(res,twitch,accessToken=''){const sid=id(32);sessions.set(sid,{twitch,accessToken,createdAt:now(),expiresAt:now()+7*86400000});res.setHeader('Set-Cookie',`sovara_session=${sid}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${7*86400}${isProduction()?'; Secure':''}`);return sid;}
function clearSession(req,res){const sid=parseCookies(req).sovara_session;if(sid)sessions.delete(sid);res.setHeader('Set-Cookie',`sovara_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${isProduction()?'; Secure':''}`);}
function isAdmin(twitch,config){if(!twitch)return false;if(config.adminTwitchUserId)return String(twitch.id)===String(config.adminTwitchUserId);return safeEqual(twitch.login,config.adminTwitchLogin);}
function maybeBindAdmin(twitch){const c=loadConfig();if(!c.adminTwitchUserId&&safeEqual(twitch.login,c.adminTwitchLogin)){c.adminTwitchUserId=String(twitch.id);saveConfig(c);}}
function sendJson(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Content-Length':Buffer.byteLength(body)});res.end(body);}
function sendText(res,status,text,type='text/plain; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(text);}
async function bodyJson(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>1e6){reject(Error('body too large'));req.destroy();}});req.on('end',()=>{try{resolve(b?JSON.parse(b):{});}catch(e){reject(e);}});req.on('error',reject);});}
async function postForm(url,params){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={message:text}}return {ok:r.ok,status:r.status,data};}
async function validateTwitchToken(token,clientId){const r=await fetch('https://id.twitch.tv/oauth2/validate',{headers:{Authorization:`OAuth ${token}`}});if(!r.ok)throw Error('Twitch не подтвердил OAuth token.');const v=await r.json();if(String(v.client_id)!==String(clientId))throw Error('OAuth token выпущен для другого Client ID.');if(!v.user_id||!v.login)throw Error('Twitch не вернул пользователя.');let displayName=v.login,avatar='';try{const u=await fetch('https://api.twitch.tv/helix/users',{headers:{Authorization:`Bearer ${token}`,'Client-Id':clientId}});if(u.ok){const j=await u.json();if(j.data&&j.data[0]){displayName=j.data[0].display_name||displayName;avatar=j.data[0].profile_image_url||'';}}}catch{}return {id:String(v.user_id),login:String(v.login),displayName:String(displayName),avatar:String(avatar)};}
function requireAuth(req,res){const s=sessionFor(req);if(!s){sendJson(res,401,{error:'AUTH_REQUIRED'});return null;}return s;}
function requireAdmin(req,res){const s=requireAuth(req,res);if(!s)return null;if(!isAdmin(s.twitch,loadConfig())){sendJson(res,403,{error:'ADMIN_REQUIRED'});return null;}return s;}

async function twitchApi(url,token){const c=loadConfig();const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`,'Client-Id':c.clientId}});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={message:text}}if(!r.ok)throw Error(data.message||`Twitch API ${r.status}`);return data;}
async function refreshStreamStatus(force=false){if(!runtime.adminToken||!runtime.adminTwitch){runtime.streamStatus='NO_AUTH';runtime.streamOnline=false;return runtimeSummary();}if(!force&&now()-runtime.lastStreamCheck<15000)return runtimeSummary();runtime.lastStreamCheck=now();try{const d=await twitchApi(`https://api.twitch.tv/helix/streams?user_id=${encodeURIComponent(runtime.adminTwitch.id)}`,runtime.adminToken);const stream=d.data&&d.data[0];runtime.streamOnline=!!stream;runtime.streamStatus=stream?'ONLINE':'OFFLINE';runtime.streamStartedAt=stream?stream.started_at:null;runtime.lastStreamError='';}catch(e){runtime.streamStatus='ERROR';runtime.lastStreamError=e.message;}return runtimeSummary();}
function runtimeSummary(){return {websocketAvailable:!!WebSocket,eventSubStatus:runtime.wsStatus,chatSubscribed:runtime.chatSubscribed,streamSubscribed:runtime.streamSubscribed,streamStatus:runtime.streamStatus,streamOnline:runtime.streamOnline,streamStartedAt:runtime.streamStartedAt,lastStreamCheck:runtime.lastStreamCheck,lastStreamError:runtime.lastStreamError,lastChatAt:runtime.lastChatAt,lastWatchtimePoll:runtime.lastWatchtimePoll,lastWatchtimeUsers:runtime.lastWatchtimeUsers,lastWatchtimeError:runtime.lastWatchtimeError,adminRuntimeReady:!!runtime.adminToken};}
async function createEventSub(type,version,condition,sessionId){const c=loadConfig();const r=await fetch('https://api.twitch.tv/helix/eventsub/subscriptions',{method:'POST',headers:{Authorization:`Bearer ${runtime.adminToken}`,'Client-Id':c.clientId,'Content-Type':'application/json'},body:JSON.stringify({type,version,condition,transport:{method:'websocket',session_id:sessionId}})});const tx=await r.text();let d;try{d=JSON.parse(tx)}catch{d={message:tx}}if(!r.ok)throw Error(`${type}: ${d.message||r.status}`);return d;}
async function subscribeEventSub(sessionId){if(!runtime.adminTwitch||!runtime.adminToken)return;const bid=runtime.adminTwitch.id;runtime.chatSubscribed=false;runtime.streamSubscribed=false;const errors=[];try{await createEventSub('channel.chat.message','1',{broadcaster_user_id:bid,user_id:bid},sessionId);runtime.chatSubscribed=true;}catch(e){errors.push(e.message);}try{await createEventSub('stream.online','1',{broadcaster_user_id:bid},sessionId);await createEventSub('stream.offline','1',{broadcaster_user_id:bid},sessionId);runtime.streamSubscribed=true;}catch(e){errors.push(e.message);}if(errors.length)runtime.lastStreamError=errors.join(' | ');}
function closeEventSub(){if(runtime.reconnectTimer){clearTimeout(runtime.reconnectTimer);runtime.reconnectTimer=null;}if(runtime.ws){try{runtime.ws.removeAllListeners();runtime.ws.close();}catch{}runtime.ws=null;}runtime.wsStatus='DISCONNECTED';runtime.wsSessionId='';runtime.chatSubscribed=false;runtime.streamSubscribed=false;}
function scheduleReconnect(){if(runtime.reconnectTimer||!runtime.adminToken)return;runtime.reconnectTimer=setTimeout(()=>{runtime.reconnectTimer=null;startEventSub();},5000);}
function startEventSub(reconnectUrl=''){if(!WebSocket||!runtime.adminToken||!runtime.adminTwitch)return;closeEventSub();const url=reconnectUrl||'wss://eventsub.wss.twitch.tv/ws?keepalive_timeout_seconds=30';runtime.wsStatus='CONNECTING';const ws=new WebSocket(url);runtime.ws=ws;ws.on('open',()=>{runtime.wsStatus='CONNECTED';});ws.on('message',async raw=>{let msg;try{msg=JSON.parse(String(raw));}catch{return;}const kind=msg.metadata&&msg.metadata.message_type;if(kind==='session_welcome'){runtime.wsSessionId=msg.payload.session.id;await subscribeEventSub(runtime.wsSessionId);await refreshStreamStatus(true);}else if(kind==='session_reconnect'){const u=msg.payload&&msg.payload.session&&msg.payload.session.reconnect_url;if(u)startEventSub(u);}else if(kind==='notification'){const type=msg.metadata.subscription_type,e=msg.payload.event||{};if(type==='stream.online'){runtime.streamOnline=true;runtime.streamStatus='ONLINE';runtime.streamStartedAt=e.started_at||new Date().toISOString();runtime.lastStreamCheck=now();}else if(type==='stream.offline'){runtime.streamOnline=false;runtime.streamStatus='OFFLINE';runtime.streamStartedAt=null;runtime.lastStreamCheck=now();}else if(type==='channel.chat.message'){const state=loadState();processChatMessage(state,{userId:e.chatter_user_id,login:e.chatter_user_login,displayName:e.chatter_user_name,messageId:e.message_id,text:e.message&&e.message.text||''},{streamOnline:runtime.streamOnline,source:'eventsub'});saveState(state);}}});ws.on('close',()=>{if(runtime.ws===ws){runtime.ws=null;runtime.wsStatus='DISCONNECTED';runtime.chatSubscribed=false;runtime.streamSubscribed=false;scheduleReconnect();}});ws.on('error',e=>{runtime.wsStatus='ERROR';runtime.lastStreamError=e.message||'WebSocket error';});}
function setAdminRuntime(twitch,token){runtime.adminTwitch=twitch;runtime.adminToken=token||'';if(token){startEventSub();refreshStreamStatus(true);startWatchtimeLoop();}}
async function fetchAllChatters(){if(!runtime.adminToken||!runtime.adminTwitch)return [];let after='',out=[];do{const url=new URL('https://api.twitch.tv/helix/chat/chatters');url.searchParams.set('broadcaster_id',runtime.adminTwitch.id);url.searchParams.set('moderator_id',runtime.adminTwitch.id);url.searchParams.set('first','1000');if(after)url.searchParams.set('after',after);const d=await twitchApi(url.toString(),runtime.adminToken);out=out.concat(d.data||[]);after=d.pagination&&d.pagination.cursor||'';}while(after&&out.length<10000);return out;}
async function runWatchtimePoll(){runtime.lastWatchtimePoll=now();runtime.lastWatchtimeUsers=0;runtime.lastWatchtimeError='';const stateSettings=loadState().settings;if(!stateSettings.watchtimePointsEnabled){runtime.lastWatchtimeError='Начисление баллов за просмотр отключено';return;}if(!runtime.adminToken||!runtime.adminTwitch){runtime.lastWatchtimeError='Нет Twitch авторизации админа';return;}await refreshStreamStatus(true);if(!runtime.streamOnline){runtime.lastWatchtimeError='Стрим офлайн — watchtime не начислялся';return;}try{const chatters=await fetchAllChatters();const state=loadState(),mins=Math.max(1,Math.floor(Number(state.settings.watchtimePollMinutes)||5)),ppm=Math.max(0,Math.floor(Number(state.settings.pointsPerMinute)||1));let updated=0;for(const c of chatters){const u=getOrCreateChatUser(state,{userId:c.user_id,login:c.user_login,displayName:c.user_name});if(!pointsAllowed(u))continue;u.totalWatchMinutes+=mins;applyPoints(state,u,mins*ppm,'watchtime');updated++;}runtime.lastWatchtimeUsers=updated;addAudit(state,'watchtime_poll',{chatters:chatters.length,updated,minutes:mins});saveState(state);}catch(e){runtime.lastWatchtimeError=e.message;}}
function startWatchtimeLoop(){if(runtime.watchtimeTimer)clearInterval(runtime.watchtimeTimer);const state=loadState(),mins=Math.max(2,Math.min(30,Math.floor(Number(state.settings.watchtimePollMinutes)||5)));runtime.watchtimeTimer=setInterval(runWatchtimePoll,mins*60000);}

function staticFile(req,res,urlPath){let rel=urlPath==='/'?'index.html':decodeURIComponent(urlPath).replace(/^\/+/, '');if(rel==='auth/callback')rel='index.html';const file=path.normalize(path.join(PUBLIC,rel));if(!file.startsWith(PUBLIC)){sendText(res,403,'Forbidden');return;}fs.stat(file,(err,st)=>{if(err||!st.isFile()){sendText(res,404,'Not found');return;}const ext=path.extname(file).toLowerCase(),types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});}

async function api(req,res,u){
  const config=loadConfig();
  if(req.method==='GET'&&u.pathname==='/api/status'){const state=loadState(),eligible=recalcGiveaway(state);saveState(state);const s=sessionFor(req);return sendJson(res,200,{configured:!!config.clientId,authMode:config.authMode,loginScopes:config.loginScopes||DEFAULT_SCOPES,adminLogin:config.adminTwitchLogin,redirectUri:`${requestBaseUrl(req,config)}/auth/callback`,productionMode:isProduction(),setupAllowed:!isProduction(),demoAllowed:!isProduction(),loggedIn:!!s,isAdmin:!!s&&isAdmin(s.twitch,config),viewer:s?s.twitch:null,giveaway:Object.assign({},state.giveaway,{eligibleParticipants:eligible}),settings:{pointsPerMinute:state.settings.pointsPerMinute,pointsPerMessage:state.settings.pointsPerMessage,messagePointsEnabled:state.settings.messagePointsEnabled,watchtimePointsEnabled:state.settings.watchtimePointsEnabled,countMessagesOffline:state.settings.countMessagesOffline}});}
  if(req.method==='POST'&&u.pathname==='/api/setup'){if(isProduction())return sendJson(res,403,{error:'SETUP_DISABLED_IN_PRODUCTION'});const b=await bodyJson(req),next=loadConfig();if(b.clientId!==undefined){const x=esc(b.clientId);if(x&&!/^[a-z0-9]{10,80}$/i.test(x))return sendJson(res,400,{error:'CLIENT_ID_INVALID'});next.clientId=x;}if(['device','implicit'].includes(b.authMode))next.authMode=b.authMode;if(b.loginScopes!==undefined)next.loginScopes=esc(b.loginScopes).slice(0,500)||DEFAULT_SCOPES;next.adminTwitchLogin='sovara_';saveConfig(next);return sendJson(res,200,{ok:true,configured:!!next.clientId,redirectUri:`${requestBaseUrl(req,next)}/auth/callback`});}
  if(req.method==='POST'&&u.pathname==='/api/auth/device/start'){if(!config.clientId)return sendJson(res,400,{error:'TWITCH_NOT_CONFIGURED'});const r=await postForm('https://id.twitch.tv/oauth2/device',{client_id:config.clientId,scopes:config.loginScopes||DEFAULT_SCOPES});if(!r.ok)return sendJson(res,r.status,{error:'TWITCH_DEVICE_START_FAILED',details:r.data});const attemptId=id();deviceAttempts.set(attemptId,{deviceCode:r.data.device_code,expiresAt:now()+Number(r.data.expires_in||1800)*1000,interval:Number(r.data.interval||5),lastPoll:0});return sendJson(res,200,{attemptId,userCode:r.data.user_code,verificationUri:r.data.verification_uri,expiresIn:r.data.expires_in,interval:r.data.interval});}
  if(req.method==='POST'&&u.pathname==='/api/auth/device/poll'){if(!config.clientId)return sendJson(res,400,{error:'TWITCH_NOT_CONFIGURED'});const b=await bodyJson(req),a=deviceAttempts.get(String(b.attemptId||''));if(!a||a.expiresAt<now())return sendJson(res,410,{error:'DEVICE_CODE_EXPIRED'});if(now()-a.lastPoll<Math.max(1000,a.interval*1000-500))return sendJson(res,202,{pending:true});a.lastPoll=now();const r=await postForm('https://id.twitch.tv/oauth2/token',{client_id:config.clientId,scopes:config.loginScopes||DEFAULT_SCOPES,device_code:a.deviceCode,grant_type:'urn:ietf:params:oauth:grant-type:device_code'});if(!r.ok){const code=r.data&&String(r.data.message||r.data.error||'').toLowerCase();if(r.status===400&&(code.includes('pending')||code.includes('authorization')))return sendJson(res,202,{pending:true});if(code.includes('slow')){a.interval+=2;return sendJson(res,202,{pending:true,slowDown:true});}return sendJson(res,r.status,{error:'TWITCH_DEVICE_POLL_FAILED',details:r.data});}try{const twitch=await validateTwitchToken(r.data.access_token,config.clientId);deviceAttempts.delete(String(b.attemptId));maybeBindAdmin(twitch);createSession(res,twitch,r.data.access_token);const st=loadState();getUser(st,twitch);recalcGiveaway(st);saveState(st);if(isAdmin(twitch,loadConfig()))setAdminRuntime(twitch,r.data.access_token);return sendJson(res,200,{ok:true,twitch,isAdmin:isAdmin(twitch,loadConfig())});}catch(e){return sendJson(res,400,{error:'TWITCH_VALIDATE_FAILED',message:e.message});}}
  if(req.method==='POST'&&u.pathname==='/api/auth/implicit/start'){if(!config.clientId)return sendJson(res,400,{error:'TWITCH_NOT_CONFIGURED'});const state=id(18);oauthStates.set(state,{expiresAt:now()+10*60*1000});const redirect=`${requestBaseUrl(req,config)}/auth/callback`,q=new URLSearchParams({response_type:'token',client_id:config.clientId,redirect_uri:redirect,scope:config.loginScopes||DEFAULT_SCOPES,state});return sendJson(res,200,{state,url:`https://id.twitch.tv/oauth2/authorize?${q.toString()}`,redirectUri:redirect});}
  if(req.method==='POST'&&u.pathname==='/api/auth/implicit/finish'){if(!config.clientId)return sendJson(res,400,{error:'TWITCH_NOT_CONFIGURED'});const b=await bodyJson(req),a=oauthStates.get(String(b.state||''));if(!a||a.expiresAt<now())return sendJson(res,400,{error:'OAUTH_STATE_INVALID'});oauthStates.delete(String(b.state));try{const twitch=await validateTwitchToken(String(b.accessToken||''),config.clientId);maybeBindAdmin(twitch);createSession(res,twitch,String(b.accessToken||''));const st=loadState();getUser(st,twitch);recalcGiveaway(st);saveState(st);if(isAdmin(twitch,loadConfig()))setAdminRuntime(twitch,String(b.accessToken||''));return sendJson(res,200,{ok:true,twitch,isAdmin:isAdmin(twitch,loadConfig())});}catch(e){return sendJson(res,400,{error:'TWITCH_VALIDATE_FAILED',message:e.message});}}
  if(req.method==='POST'&&u.pathname==='/api/auth/demo'){if(isProduction())return sendJson(res,404,{error:'NOT_FOUND'});const b=await bodyJson(req),admin=!!b.admin,twitch=admin?{id:'777000001',login:'sovara_',displayName:'SOVARA',avatar:''}:{id:'777000002',login:'demo_viewer',displayName:'DemoViewer',avatar:''};createSession(res,twitch,'');const st=loadState(),usr=getUser(st,twitch);if(!admin&&usr.points===0){usr.points=1847;syncTickets(usr,st.giveaway);usr.totalWatchMinutes=1312;}recalcGiveaway(st);saveState(st);return sendJson(res,200,{ok:true,twitch,isAdmin:admin});}
  if(req.method==='POST'&&u.pathname==='/api/logout'){clearSession(req,res);return sendJson(res,200,{ok:true});}
  if(req.method==='GET'&&u.pathname==='/api/me'){const s=requireAuth(req,res);if(!s)return;const st=loadState(),usr=getUser(st,s.twitch);saveState(st);return sendJson(res,200,{user:privateUser(usr),isAdmin:isAdmin(s.twitch,loadConfig())});}
  if(req.method==='PUT'&&u.pathname==='/api/me/profile'){const s=requireAuth(req,res);if(!s)return;const b=await bodyJson(req),p=Object.assign(defaultProfile(),b.profile||{});p.prizeType=esc(p.prizeType);p.steamLogin=esc(p.steamLogin).slice(0,64);p.steamCurrency=esc(p.steamCurrency).toUpperCase();p.steamFriendCode=esc(p.steamFriendCode).slice(0,20);p.steamGameUrl=esc(p.steamGameUrl).slice(0,500);p.ozonEmail=esc(p.ozonEmail).slice(0,320);p.donationGame=esc(p.donationGame).slice(0,120);p.donationAccount=esc(p.donationAccount).slice(0,200);p.contactVk=esc(p.contactVk).slice(0,300);p.contactTelegram=esc(p.contactTelegram).replace(/^https?:\/\/t\.me\//i,'@').slice(0,80);const v=profileValidation(p);if(!v.ok)return sendJson(res,422,{error:'VALIDATION',errors:v.errors});const st=loadState(),usr=getUser(st,s.twitch);usr.profile=p;usr.updatedAt=now();addAudit(st,'profile_saved',{twitchUserId:usr.twitchUserId});const eligible=recalcGiveaway(st);saveState(st);return sendJson(res,200,{ok:true,user:privateUser(usr),eligibleParticipants:eligible,giveaway:st.giveaway});}
  if(req.method==='GET'&&u.pathname==='/api/participants'){const st=loadState(),list=Object.values(st.users).map(normalizeUser).filter(x=>profileValidation(x.profile).ok&&x.tickets>0).sort((a,b)=>b.tickets-a.tickets||b.points-a.points).map(publicUser);return sendJson(res,200,{participants:list,totalTickets:list.reduce((n,x)=>n+x.tickets,0)});}

  if(req.method==='GET'&&u.pathname==='/api/admin/users'){if(!requireAdmin(req,res))return;const st=loadState(),users=Object.values(st.users).map(normalizeUser).sort((a,b)=>b.tickets-a.tickets||b.points-a.points).map(privateUser);return sendJson(res,200,{users,giveaway:st.giveaway,eligibleParticipants:countEligible(st),settings:st.settings,runtime:runtimeSummary()});}
  if(req.method==='GET'&&u.pathname==='/api/admin/runtime'){if(!requireAdmin(req,res))return;await refreshStreamStatus(true);return sendJson(res,200,{runtime:runtimeSummary(),settings:loadState().settings});}
  if(req.method==='PUT'&&u.pathname==='/api/admin/settings'){if(!requireAdmin(req,res))return;const b=await bodyJson(req),st=loadState();if(b.countMessagesOffline!==undefined)st.settings.countMessagesOffline=!!b.countMessagesOffline;if(b.messagePointsEnabled!==undefined)st.settings.messagePointsEnabled=!!b.messagePointsEnabled;if(b.watchtimePointsEnabled!==undefined)st.settings.watchtimePointsEnabled=!!b.watchtimePointsEnabled;if(b.pointsPerMessage!==undefined){const n=Math.floor(Number(b.pointsPerMessage));if(n<1||n>1000)return sendJson(res,400,{error:'BAD_POINTS_PER_MESSAGE'});st.settings.pointsPerMessage=n;}if(b.pointsPerMinute!==undefined){const n=Math.floor(Number(b.pointsPerMinute));if(n<0||n>1000)return sendJson(res,400,{error:'BAD_POINTS_PER_MINUTE'});st.settings.pointsPerMinute=n;}saveState(st);startWatchtimeLoop();return sendJson(res,200,{ok:true,settings:st.settings});}
  if(req.method==='POST'&&u.pathname==='/api/admin/user/points'){if(!requireAdmin(req,res))return;const b=await bodyJson(req),st=loadState(),usr=st.users[String(b.twitchUserId||'')];if(!usr)return sendJson(res,404,{error:'USER_NOT_FOUND'});const amount=Math.floor(Number(b.amount));if(!Number.isFinite(amount)||amount<1||amount>1000000)return sendJson(res,400,{error:'BAD_AMOUNT'});applyPoints(st,normalizeUser(usr),amount,'admin');const eligible=recalcGiveaway(st);saveState(st);return sendJson(res,200,{ok:true,user:privateUser(usr),eligibleParticipants:eligible});}
  if(req.method==='POST'&&u.pathname==='/api/admin/user/pause'){if(!requireAdmin(req,res))return;const b=await bodyJson(req),st=loadState(),usr=st.users[String(b.twitchUserId||'')];if(!usr)return sendJson(res,404,{error:'USER_NOT_FOUND'});const action=b.action==='resume'?'resume':'pause';normalizeUser(usr);usr.pointsPausedUntil=action==='resume'?0:now()+24*60*60*1000;usr.updatedAt=now();addAudit(st,action==='resume'?'points_resumed':'points_paused',{twitchUserId:usr.twitchUserId,until:usr.pointsPausedUntil});saveState(st);return sendJson(res,200,{ok:true,user:privateUser(usr)});}
  if(req.method==='POST'&&u.pathname==='/api/admin/user/winner-blacklist'){if(!requireAdmin(req,res))return;const b=await bodyJson(req),st=loadState(),usr=st.users[String(b.twitchUserId||'')];if(!usr)return sendJson(res,404,{error:'USER_NOT_FOUND'});normalizeUser(usr);const action=b.action==='remove'?'remove':'add';usr.winnerBlacklisted=action==='add';usr.winnerBlacklistedAt=action==='add'?now():0;usr.updatedAt=now();addAudit(st,action==='add'?'winner_blacklist_added':'winner_blacklist_removed',{twitchUserId:usr.twitchUserId});saveState(st);return sendJson(res,200,{ok:true,user:privateUser(usr),winnerPoolTickets:winnerPool(st).reduce((n,x)=>n+x.tickets,0)});}
  if(req.method==='GET'&&u.pathname==='/api/admin/user/history'){if(!requireAdmin(req,res))return;const st=loadState(),usr=st.users[String(u.searchParams.get('id')||'')];if(!usr)return sendJson(res,404,{error:'USER_NOT_FOUND'});normalizeUser(usr);return sendJson(res,200,{user:{twitchUserId:usr.twitchUserId,login:usr.login,displayName:usr.displayName},messages:usr.chatHistory.slice().reverse()});}
  if(req.method==='POST'&&u.pathname==='/api/admin/chat/simulate'){if(!requireAdmin(req,res))return;const b=await bodyJson(req),st=loadState(),usr=st.users[String(b.twitchUserId||'')];if(!usr)return sendJson(res,404,{error:'USER_NOT_FOUND'});const result=processChatMessage(st,{userId:usr.twitchUserId,login:usr.login,displayName:usr.displayName,messageId:'sim-'+id(8),text:String(b.text||'Тестовое сообщение').slice(0,500)},{streamOnline:runtime.streamOnline,source:'simulator'});saveState(st);return sendJson(res,200,{ok:true,result,streamOnline:runtime.streamOnline,countMessagesOffline:st.settings.countMessagesOffline});}
  if(req.method==='POST'&&u.pathname==='/api/admin/watchtime/run'){if(!requireAdmin(req,res))return;await runWatchtimePoll();return sendJson(res,200,{ok:true,runtime:runtimeSummary()});}
  if(req.method==='POST'&&u.pathname==='/api/admin/giveaway/draw'){if(!requireAdmin(req,res))return;const st=loadState();if(st.giveaway.winner)return sendJson(res,409,{error:'WINNER_ALREADY_SELECTED',winner:st.giveaway.winner});const winner=drawWinner(st);if(!winner)return sendJson(res,409,{error:'NO_ELIGIBLE_WINNER_POOL'});st.giveaway.winner=winner;addAudit(st,'winner_selected',{twitchUserId:winner.twitchUserId,drawTicket:winner.drawTicket,totalEligibleTickets:winner.totalEligibleTickets});saveState(st);return sendJson(res,200,{ok:true,winner});}
  if(req.method==='POST'&&u.pathname==='/api/admin/demo/add'){if(isProduction())return sendJson(res,404,{error:'NOT_FOUND'});if(!requireAdmin(req,res))return;const st=loadState();let n=Object.keys(st.users).filter(x=>x.startsWith('990')).length+1,uid='990'+String(n).padStart(7,'0');st.users[uid]=normalizeUser({twitchUserId:uid,login:`testviewer${n}`,displayName:`TestViewer${n}`,avatar:'',points:300+n*50,tickets:0,totalWatchMinutes:200,profile:{...defaultProfile(),prizeType:'steam_balance',steamLogin:`test${n}`,steamCurrency:'RUB',contactTelegram:`@testviewer${n}`},chatHistory:[],pointsPausedUntil:0,createdAt:now(),updatedAt:now()});syncTickets(st.users[uid],st.giveaway);const eligible=recalcGiveaway(st);saveState(st);return sendJson(res,200,{ok:true,eligibleParticipants:eligible,giveaway:st.giveaway});}
  return sendJson(res,404,{error:'API_NOT_FOUND'});
}

const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/'))return await api(req,res,u);staticFile(req,res,u.pathname);}catch(e){console.error(e);if(!res.headersSent)sendJson(res,500,{error:'INTERNAL',message:e.message});else res.end();}});
const config=loadConfig();const listenPort=Number(process.env.PORT||config.port)||4177;server.listen(listenPort,'0.0.0.0',()=>{console.log('\n  SOVARA Giveaway Web v0.7 Railway');console.log(`  Listening on 0.0.0.0:${listenPort}`);console.log('');if(!WebSocket)console.log('  ⚠ Модуль ws не установлен: Twitch EventSub чат отключён. Запусти npm install.');if(!config.clientId)console.log('  Twitch Client ID пока не настроен — открой сайт и нажми «⚙ Twitch».');else console.log(`  Twitch OAuth: ${config.authMode} / Client ID ${config.clientId.slice(0,5)}…`);console.log('  Для остановки: Ctrl+C\n');});
